"""
ML TRADING BOT - EDUCATIONAL DEMO
=================================

**Disclaimer:**
This is an educational tool and not intended for live trading. The machine
learning model is trained on synthetic data generated by the `PerfectMarketSimulator`.
Its performance in this simulation is NOT indicative of real-world trading results.
Real markets are far more complex and unpredictable.
"""
import numpy as np
import time
import os
import json
from datetime import datetime as dt, timedelta
from typing import Dict, List, Tuple, Optional
import random
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib


# ============================================================================
# PERFECT CONFIGURATION
# ============================================================================

class PerfectTradingConfig:
    """Configuration for the options trading bot."""

    # Symbol
    SYMBOL = "NSE:NIFTY50-INDEX"
    OPTIONS_STRIKE_STEP = 50  # e.g., NIFTY strikes are 50 points apart

    # Account - Balanced
    INITIAL_BALANCE = 1000000
    POSITION_SIZE = 75  # Number of contracts per trade
    MAX_POSITIONS = 1  # Simplified to one position at a time
    RESET_COLOR = "\033[0m"

    # Timing - Optimal
    UPDATE_INTERVAL = 15  # Good pace

    # Balanced Strategy
    RSI_PERIOD = 10
    RSI_OVERBOUGHT = 70
    RSI_OVERSOLD = 30
    EMA_SHORT = 8
    EMA_LONG = 21
    MACD_FAST = 8
    MACD_SLOW = 17
    MACD_SIGNAL = 7

    # Smart Risk Management
    STOP_LOSS_PCT = 1.5
    TAKE_PROFIT_PCT = 3.0
    TRAILING_STOP_PCT = 0.5  # Trailing stop after profit

    # Trading Behavior
    MIN_CONFIDENCE = 0.0
    VOLATILITY_MULTIPLIER = 2.0
    INITIAL_PRICES = 50

    # Profit Taking
    MIN_PROFIT_TO_SELL = 1.0  # Minimum 1% profit to consider selling
    PARTIAL_PROFIT_TAKING = True  # Take partial profits
    PARTIAL_SELL_PCT = 0.5  # Sell 50% at take profit


# ============================================================================
# ML CONFIGURATION
# ============================================================================

class MLConfig:
    """Configuration for the ML model and feature engineering."""
    MODEL_FILENAME = "options_trading_model.joblib"
    LOOKAHEAD_PERIOD = 5  # Predict 5 cycles into the future
    TRAINING_DATA_SIZE = 5000  # Number of data points for training

# ============================================================================
# FEATURE ENGINEERING
# ============================================================================

def create_features(prices: List[float], config: PerfectTradingConfig) -> pd.DataFrame:
    """Create features from price data for the ML model."""
    if len(prices) < config.EMA_LONG:
        return pd.DataFrame()

    df = pd.DataFrame({'price': prices})

    # --- Standard Indicators ---
    # RSI
    delta = df['price'].diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=config.RSI_PERIOD).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=config.RSI_PERIOD).mean()
    rs = gain / loss
    df['rsi'] = 100 - (100 / (1 + rs))
    df['rsi'] = df['rsi'].replace([np.inf, -np.inf], np.nan).fillna(50) # Handle inf and fill NaN

    # EMAs
    df['ema_short'] = df['price'].ewm(span=config.EMA_SHORT, adjust=False).mean()
    df['ema_long'] = df['price'].ewm(span=config.EMA_LONG, adjust=False).mean()
    df['ema_diff'] = (df['ema_short'] - df['ema_long']) / df['price']

    # MACD
    ema_fast = df['price'].ewm(span=config.MACD_FAST, adjust=False).mean()
    ema_slow = df['price'].ewm(span=config.MACD_SLOW, adjust=False).mean()
    df['macd'] = ema_fast - ema_slow
    df['macd_signal'] = df['macd'].ewm(span=config.MACD_SIGNAL, adjust=False).mean()
    df['macd_hist'] = df['macd'] - df['macd_signal']

    # --- Price-based Features ---
    # Price change (Momentum)
    df['momentum_1'] = df['price'].pct_change(periods=1)
    df['momentum_5'] = df['price'].pct_change(periods=5)
    df['momentum_10'] = df['price'].pct_change(periods=10)

    # Volatility (standard deviation of returns)
    df['volatility_5'] = df['momentum_1'].rolling(window=5).std()
    df['volatility_10'] = df['momentum_1'].rolling(window=10).std()

    # Distance from moving averages
    df['dist_ema_short'] = (df['price'] - df['ema_short']) / df['price']
    df['dist_ema_long'] = (df['price'] - df['ema_long']) / df['price']

    # --- Target Variable ---
    # The target is the future price direction.
    # 1 for buy (price will increase), -1 for sell (price will decrease), 0 for hold.
    future_price = df['price'].shift(-MLConfig.LOOKAHEAD_PERIOD)
    price_change = (future_price - df['price']) / df['price']

    df['target'] = 0
    df.loc[price_change > 0.005, 'target'] = 1  # Buy if price increases by 0.5%
    df.loc[price_change < -0.005, 'target'] = -1 # Sell if price decreases by 0.5%

    # Fill initial NaN values and return
    return df.dropna().reset_index(drop=True)


# ============================================================================
# MODEL TRAINING
# ============================================================================

def train_model(config: PerfectTradingConfig, ml_config: MLConfig) -> RandomForestClassifier:
    """Train and save the ML model."""
    # Check if a trained model already exists
    if os.path.exists(ml_config.MODEL_FILENAME):
        print(f"🧠 Loading existing model from {ml_config.MODEL_FILENAME}...")
        return joblib.load(ml_config.MODEL_FILENAME)

    print("🤖 No existing model found. Training a new one...")
    # 1. Generate a large dataset for training
    print(f"📊 Generating {ml_config.TRAINING_DATA_SIZE} data points for training...")
    market = PerfectMarketSimulator(config)
    for _ in range(ml_config.TRAINING_DATA_SIZE - len(market.underlying_prices)):
        market.generate_price_and_options()

    # 2. Create features and target from the underlying asset's prices
    print("✨ Engineering features...")
    df = create_features(market.get_price_history(ml_config.TRAINING_DATA_SIZE), config)
    if df.empty:
        raise ValueError("Could not create features for training. Not enough data.")

    # 3. Split data into training and testing sets
    X = df.drop(['price', 'target'], axis=1)
    y = df['target']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

    # 4. Train the model
    print("💪 Training the RandomForestClassifier...")
    model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1, class_weight='balanced')
    model.fit(X_train, y_train)

    # 5. Evaluate the model
    accuracy = model.score(X_test, y_test)
    print(f"✅ Model training complete. Accuracy: {accuracy:.2%}")

    # 6. Save the model
    print(f"💾 Saving model to {ml_config.MODEL_FILENAME}...")
    joblib.dump(model, ml_config.MODEL_FILENAME)

    return model


# ============================================================================
# PERFECT MARKET SIMULATOR - FIXED
# ============================================================================

class PerfectMarketSimulator:
    """
    Simulates an underlying asset (like an index) and a corresponding options chain.
    """
    def __init__(self, config: PerfectTradingConfig):
        self.config = config
        self.support = 17500
        self.resistance = 18500
        self.underlying_prices = self._generate_trending_prices()
        self.trend_direction = random.choice([-1, 1]) * 0.00005
        self.volatility = 0.001 * config.VOLATILITY_MULTIPLIER
        self.last_price = self.underlying_prices[-1]
        self.cycle = 0

    def _generate_trending_prices(self) -> List[float]:
        """Generate trending initial prices for the underlying asset."""
        print(f"📊 Generating {self.config.INITIAL_PRICES} trending prices for {self.config.SYMBOL}...")
        prices = []
        current = 18000.0  # A realistic starting point for an index
        trend = random.uniform(-0.0001, 0.0001)

        for _ in range(self.config.INITIAL_PRICES):
            change = trend + np.random.normal(0, 0.0005)
            current *= (1 + change)
            current = max(self.support, min(self.resistance, current))
            prices.append(round(current, 2))

        trend_direction = "UP" if prices[-1] > prices[0] else "DOWN"
        print(f"✅ Initial trend: {trend_direction} ({prices[0]:.2f} → {prices[-1]:.2f})")
        return prices

    def generate_price_and_options(self) -> Tuple[float, List[Dict]]:
        """Generate a new price for the underlying and a corresponding options chain."""
        self.cycle += 1
        distance_to_mid = (18000 - self.last_price) / 18000
        mean_reversion = distance_to_mid * 0.0001
        trend = self.trend_direction
        volatility = self.volatility * (1 + abs(distance_to_mid))
        change = trend + mean_reversion + np.random.normal(0, volatility)
        new_price = self.last_price * (1 + change)

        if new_price < self.support:
            new_price = self.support + random.uniform(0, 20)
        elif new_price > self.resistance:
            new_price = self.resistance - random.uniform(0, 20)

        new_price = round(new_price, 2)
        self.last_price = new_price
        self.underlying_prices.append(new_price)

        if len(self.underlying_prices) > 2000:
            self.underlying_prices = self.underlying_prices[-2000:]

        options_chain = self._generate_options_chain(new_price)
        return new_price, options_chain

    def _generate_options_chain(self, underlying_price: float) -> List[Dict]:
        """Generate a simplified options chain around the current underlying price."""
        step = self.config.OPTIONS_STRIKE_STEP
        atm_strike = round(underlying_price / step) * step
        chain = []
        for i in range(-3, 4):
            strike = atm_strike + (i * step)
            # Calculate simple intrinsic value based prices
            call_premium = max(0.05, round(underlying_price - strike, 2)) + random.uniform(1, 5)
            put_premium = max(0.05, round(strike - underlying_price, 2)) + random.uniform(1, 5)

            chain.append({'symbol': f"NIFTY_CE_{strike}", 'type': 'CE', 'strike': strike, 'price': round(call_premium, 2)})
            chain.append({'symbol': f"NIFTY_PE_{strike}", 'type': 'PE', 'strike': strike, 'price': round(put_premium, 2)})
        return chain

    def get_price_history(self, count: int = 100) -> List[float]:
        """Get recent price history of the underlying asset."""
        return self.underlying_prices[-count:]


# ============================================================================
# OPTIONS ML TRADING STRATEGY
# ============================================================================

class OptionsMLStrategy:
    """
    An options trading strategy that uses an ML model to predict the direction
    of the underlying asset and then buys calls or puts accordingly.
    """
    def __init__(self, config: PerfectTradingConfig, model: RandomForestClassifier):
        self.config = config
        self.model = model
        self.feature_names = model.feature_names_in_

    def generate_signal(self, underlying_prices: List[float], options_chain: List[Dict], current_positions: List[Dict]) -> Tuple[Optional[Dict], Optional[int], float, List[str]]:
        """
        Generate a signal to buy a call/put or sell an existing position.
        Returns: (option_to_buy, position_index_to_sell, confidence, reasons)
        """
        if len(underlying_prices) < self.config.EMA_LONG + 10:
            return None, None, 0.0, ["Not enough data for prediction"]

        # 1. Predict the direction of the underlying asset
        features_df = create_features(underlying_prices, self.config)
        if features_df.empty:
            return None, None, ["Feature creation failed"]

        latest_features = features_df.tail(1).drop(columns=['price', 'target'], errors='ignore')
        latest_features = latest_features[self.feature_names]

        prediction = self.model.predict(latest_features)[0]
        confidence = max(self.model.predict_proba(latest_features)[0])
        signal = int(prediction)

        # 2. Decide whether to sell an existing position
        if current_positions:
            # Simple strategy: if the model predicts a reversal, sell the position.
            position = current_positions[0] # Assuming one position at a time
            if (signal == -1 and position['type'] == 'CE') or \
               (signal == 1 and position['type'] == 'PE'):
                reason = f"ML predicts reversal. Selling {position['symbol']}."
                return None, 0, confidence, [reason]

        # 3. Decide whether to buy a new option
        if not current_positions and confidence > self.config.MIN_CONFIDENCE:
            underlying_price = underlying_prices[-1]
            atm_strike = round(underlying_price / self.config.OPTIONS_STRIKE_STEP) * self.config.OPTIONS_STRIKE_STEP

            option_to_buy = None
            if signal == 1: # Buy Call
                option_to_buy = next((o for o in options_chain if o['type'] == 'CE' and o['strike'] == atm_strike), None)
            elif signal == -1: # Buy Put
                option_to_buy = next((o for o in options_chain if o['type'] == 'PE' and o['strike'] == atm_strike), None)

            if option_to_buy:
                reason = f"ML predicts UP, buying Call." if signal == 1 else f"ML predicts DOWN, buying Put."
                return option_to_buy, None, confidence, [reason + f" (Conf: {confidence:.1%})"]

        return None, None, confidence, ["HOLD: No clear signal or position held"]


# ============================================================================
# PERFECT TRADING BOT
# ============================================================================

class PerfectTradingBot:
    """An options trading bot powered by an ML model."""

    def __init__(self, config: PerfectTradingConfig, ml_config: MLConfig):
        self.config = config
        self.ml_config = ml_config

        # Initialize components
        print("\n" + "=" * 60)
        print("🤖 INITIALIZING OPTIONS ML TRADING BOT")
        print("=" * 60)

        # Train or load the model
        self.model = train_model(config, ml_config)

        self.market = PerfectMarketSimulator(config)
        self.strategy = OptionsMLStrategy(config, self.model)

        # Trading state
        self.balance = config.INITIAL_BALANCE
        self.positions = []  # List of dicts with additional info
        self.trade_history = []

        # Statistics
        self.cycle = 0
        self.start_time = dt.now()
        self.total_pnl = 0.0
        self.total_trades = 0
        self.winning_trades = 0
        self.total_buys = 0
        self.total_sells = 0

        # Risk management
        self.max_drawdown = 0.0
        self.peak_portfolio = config.INITIAL_BALANCE

        # Display
        print("\n" + "=" * 60)
        print("🎯 PERFECT TRADING BOT - BALANCED STRATEGY")
        print("=" * 60)
        print(f"📊 Symbol: {config.SYMBOL}")
        print(f"💰 Initial Balance: ₹{config.INITIAL_BALANCE:,.2f}")
        print(f"⚡ Update Interval: {config.UPDATE_INTERVAL} seconds")
        print(f"🎯 Strategy: Balanced RSI/EMA with Profit Taking")
        print(f"📈 Position Size: {config.POSITION_SIZE} shares")
        print(f"🛡️  Stop Loss: {config.STOP_LOSS_PCT}% | Take Profit: {config.TAKE_PROFIT_PCT}%")
        print(f"💰 Partial Profit Taking: {'ENABLED' if config.PARTIAL_PROFIT_TAKING else 'DISABLED'}")
        print("=" * 60)

    def execute_buy(self, option: Dict, confidence: float, reasons: List[str]) -> bool:
        """Execute an options buy order."""
        if len(self.positions) >= self.config.MAX_POSITIONS:
            print("  ⚠️  Max positions reached - cannot buy")
            return False

        position_size = self.config.POSITION_SIZE
        cost = position_size * option['price']

        if self.balance >= cost:
            self.balance -= cost
            self.positions.append({
                'symbol': option['symbol'],
                'type': option['type'],
                'quantity': position_size,
                'entry_price': option['price'],
                'entry_time': dt.now(),
                'stop_loss': option['price'] * (1 - self.config.STOP_LOSS_PCT / 100),
                'take_profit': option['price'] * (1 + self.config.TAKE_PROFIT_PCT / 100),
                'highest_price': option['price'],
                'reasons': reasons
            })

            self.total_trades += 1
            self.total_buys += 1
            print(f"\n  🟢 BUY #{self.total_trades} ({option['symbol']})")
            print(f"     Quantity: {position_size} contracts")
            print(f"     Price: ₹{option['price']:.2f}")
            print(f"     Cost: ₹{cost:,.2f}")
            print(f"     Confidence: {confidence:.1%}")
            return True
        else:
            print(f"  ⚠️  Insufficient funds to buy {option['symbol']}")
            return False

    def check_and_execute_sells(self, options_chain: List[Dict]) -> List[float]:
        """Check for stop loss, take profit, and trailing stop triggers for options."""
        pnls = []
        positions_to_remove = []

        for i, pos in enumerate(self.positions):
            current_option = next((o for o in options_chain if o['symbol'] == pos['symbol']), None)
            if not current_option:
                continue # Option may have expired or is not in the current chain

            current_price = current_option['price']
            pos['highest_price'] = max(pos['highest_price'], current_price)

            if current_price <= pos['stop_loss']:
                pnl = self._execute_sell(i, current_price, "STOP_LOSS")
                pnls.append(pnl)
                positions_to_remove.append(i)
            elif current_price >= pos['take_profit']:
                pnl = self._execute_sell(i, current_price, "TAKE_PROFIT")
                pnls.append(pnl)
                positions_to_remove.append(i)
            elif self.config.TRAILING_STOP_PCT > 0:
                trail_stop = pos['highest_price'] * (1 - self.config.TRAILING_STOP_PCT / 100)
                if current_price <= trail_stop:
                    pnl = self._execute_sell(i, current_price, "TRAILING_STOP")
                    pnls.append(pnl)
                    positions_to_remove.append(i)

        # This part of the original code is now handled in run_cycle
        # for i in sorted(positions_to_remove, reverse=True):
        #     self.positions.pop(i)
        return positions_to_remove, pnls

    def _execute_sell(self, idx: int, price: float, reason: str) -> float:
        """Execute sell of an entire options position."""
        pos = self.positions[idx]
        revenue = pos['quantity'] * price
        pnl = revenue - (pos['quantity'] * pos['entry_price'])
        self.balance += revenue
        self.total_pnl += pnl
        self.total_trades += 1
        self.total_sells += 1
        if pnl > 0: self.winning_trades += 1

        print(f"\n  🔴 SELL #{self.total_trades} ({pos['symbol']})")
        print(f"     Price: ₹{price:.2f} | Entry: ₹{pos['entry_price']:.2f}")
        pnl_color = "\033[92m" if pnl > 0 else "\033[91m"
        print(f"     P&L: {pnl_color}₹{pnl:+,.2f}{self.config.RESET_COLOR}")
        print(f"     Reason: {reason}")
        return pnl

    def run_cycle(self) -> Dict:
        """Run one options trading cycle."""
        self.cycle += 1
        underlying_price, options_chain = self.market.generate_price_and_options()
        price_history = self.market.get_price_history(200)

        # Automatic sells (SL/TP)
        auto_sell_indices, auto_sell_pnls = self.check_and_execute_sells(options_chain)

        # ML Signal Generation
        option_to_buy, idx_to_sell, confidence, reasons = self.strategy.generate_signal(price_history, options_chain, self.positions)

        signal_executed = False
        signal_pnl = 0.0

        if option_to_buy:
            signal_executed = self.execute_buy(option_to_buy, confidence, reasons)
        elif idx_to_sell is not None:
            option_price = next((o['price'] for o in options_chain if o['symbol'] == self.positions[idx_to_sell]['symbol']), self.positions[idx_to_sell]['entry_price'])
            signal_pnl = self._execute_sell(idx_to_sell, option_price, " ".join(reasons))
            auto_sell_indices.append(idx_to_sell)
            signal_executed = True

        # Clean up sold positions
        for i in sorted(list(set(auto_sell_indices)), reverse=True):
            if i < len(self.positions):
                self.positions.pop(i)

        portfolio_value = self._calculate_portfolio_value(options_chain)
        self._update_drawdown(portfolio_value)

        return {
            'cycle': self.cycle,
            'timestamp': dt.now(),
            'price': underlying_price,
            'portfolio_value': portfolio_value,
            'positions': len(self.positions),
            'total_pnl': self.total_pnl,
            'reasons': reasons,
            'options_chain': options_chain
        }

    def _calculate_portfolio_value(self, options_chain: List[Dict]) -> float:
        """Calculate total portfolio value based on current option prices."""
        position_value = 0
        for pos in self.positions:
            current_option = next((o for o in options_chain if o['symbol'] == pos['symbol']), None)
            if current_option:
                position_value += pos['quantity'] * current_option['price']
            else: # If option expires or disappears, value is entry price (conservative)
                position_value += pos['quantity'] * pos['entry_price']
        return self.balance + position_value

    def _calculate_drawdown(self, portfolio_value: float) -> float:
        """Calculate current drawdown."""
        if portfolio_value > self.peak_portfolio:
            self.peak_portfolio = portfolio_value
            return 0.0
        else:
            return (self.peak_portfolio - portfolio_value) / self.peak_portfolio * 100

    def _update_drawdown(self, portfolio_value: float):
        """Update maximum drawdown."""
        current_dd = self._calculate_drawdown(portfolio_value)
        if current_dd > self.max_drawdown:
            self.max_drawdown = current_dd

    def display_status(self, data: Dict):
        """Display status information for the options bot."""
        print(f"\n[Cycle {data['cycle']:03d}] {data['timestamp'].strftime('%H:%M:%S')}")
        print("-" * 60)
        price_str = f"💰 Underlying ({self.config.SYMBOL}): ₹{data['price']:.2f}"
        print(price_str)
        print(f"📈 Portfolio: ₹{data['portfolio_value']:,.2f}")
        pnl_color = "\033[92m" if data['total_pnl'] >= 0 else "\033[91m"
        print(f"🎯 Total P&L: {pnl_color}₹{data['total_pnl']:+,.2f}{self.config.RESET_COLOR}")

        if data['reasons']:
            print(f"   Signal: {data['reasons'][0]}")

        if self.positions:
            print(f"\n📦 Open Positions ({len(self.positions)}):")
            for pos in self.positions:
                current_option = next((o for o in data['options_chain'] if o['symbol'] == pos['symbol']), None)
                current_price = current_option['price'] if current_option else pos['entry_price']
                unrealized_pnl = (current_price - pos['entry_price']) * pos['quantity']
                pnl_color = "\033[92m" if unrealized_pnl >= 0 else "\033[91m"
                print(f"  - {pos['symbol']}: {pos['quantity']} @ ₹{pos['entry_price']:.2f} | Current: ₹{current_price:.2f}")
                print(f"    Unrealized P&L: {pnl_color}₹{unrealized_pnl:+,.2f}{self.config.RESET_COLOR}")

    def run(self, duration_hours: float = 0.5):
        """Run the perfect trading bot."""
        print(f"\n{'=' * 60}")
        print(f"🚀 PERFECT TRADING SESSION")
        print(f"{'=' * 60}")

        end_time = self.start_time + timedelta(hours=min(duration_hours, 2))  # Max 2 hours

        print(f"⏰ Session end time: {end_time.strftime('%H:%M:%S')}")
        print(f"   ({min(duration_hours, 2)} hours)")
        print(f"\n🎯 Starting balanced trading...")

        try:
            while dt.now() < end_time:
                # Run cycle
                cycle_data = self.run_cycle()

                # Display
                self.display_status(cycle_data)

                # Time info
                elapsed = (dt.now() - self.start_time).seconds / 3600
                remaining = (end_time - dt.now()).seconds / 3600

                print(f"\n{'=' * 50}")
                print(f"⏱️  Elapsed: {elapsed:.2f}h | Remaining: {remaining:.2f}h")
                print(f"⏳ Next update in {self.config.UPDATE_INTERVAL} seconds...")

                time.sleep(self.config.UPDATE_INTERVAL)

        except KeyboardInterrupt:
            print("\n\n🛑 Trading stopped by user")

        self.show_summary()

    def show_summary(self):
        """Show a summary of the options trading session."""
        print(f"\n{'=' * 60}")
        print(f"📊 OPTIONS TRADING SUMMARY")
        print(f"{'=' * 60}")

        _, options_chain = self.market.generate_price_and_options()
        portfolio_value = self._calculate_portfolio_value(options_chain)
        total_return = ((portfolio_value - self.config.INITIAL_BALANCE) / self.config.INITIAL_BALANCE) * 100

        print(f"\n📈 PERFORMANCE:")
        print(f"  - Final Portfolio: ₹{portfolio_value:,.2f}")
        print(f"  - Total Return: {total_return:+.2f}%")
        print(f"  - Total P&L: ₹{self.total_pnl:+,.2f}")
        print(f"  - Max Drawdown: {self.max_drawdown:.2f}%")
        print(f"\n{'=' * 60}")
        print("SESSION COMPLETE")
        print(f"{'=' * 60}")


# ============================================================================
# MAIN - PERFECT
# ============================================================================

def main():
    """Main ML trading bot."""
    print("\n" + "=" * 60)
    print("🎯 ML TRADING BOT 🎯")
    print("=" * 60)

    print("\n📊 This bot features:")
    print("  • ML-driven BUY/SELL signals (RandomForestClassifier)")
    print("  • Automatic stop loss & take profit")
    print("  • On-demand model training")
    print("  • Realistic market simulation")

    # Create configs
    config = PerfectTradingConfig()
    ml_config = MLConfig()

    # Get duration (sensible limit)
    try:
        max_duration = 2  # Maximum 2 hours for testing
        prompt = f"\n⏰ Enter duration in hours (0.25 to {max_duration}): "
        duration = float(input(prompt).strip() or "0.5")
        duration = min(max(0.25, duration), max_duration)  # Clamp between 0.25 and 2
    except:
        duration = 0.5

    # Create and run
    bot = PerfectTradingBot(config, ml_config)

    print(f"\n🚀 Starting in 3 seconds...")
    time.sleep(3)

    bot.run(duration_hours=duration)


# ============================================================================
# QUICK 30-MINUTE TEST
# ============================================================================

def quick_test():
    """30-minute ML trading test."""
    print("\n" + "=" * 60)
    print("⚡ 30-MINUTE ML TRADING TEST")
    print("=" * 60)

    config = PerfectTradingConfig()
    ml_config = MLConfig()

    bot = PerfectTradingBot(config, ml_config)

    # Run for 30 minutes
    bot.run(duration_hours=0.5)


# ============================================================================
# SUPER QUICK 5-MINUTE DEMO
# ============================================================================

def quick_demo():
    """5-minute demo to see immediate action."""
    print("\n" + "=" * 60)
    print("🚀 5-MINUTE QUICK DEMO")
    print("=" * 60)

    config = PerfectTradingConfig()
    ml_config = MLConfig()
    config.UPDATE_INTERVAL = 5  # Faster for demo

    bot = PerfectTradingBot(config, ml_config)

    # Run for 5 minutes
    bot.run(duration_hours=0.083)


# ============================================================================
# SCRIPT ENTRY
# ============================================================================

if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        if sys.argv[1] == "test":
            quick_test()
        elif sys.argv[1] == "demo":
            quick_demo()
        else:
            print(f"Usage: python {sys.argv[0]} [test|demo]")
            print("  test: 30-minute balanced test")
            print("  demo: 5-minute quick demo")
            print("  (no argument): Full interactive mode")
    else:
        main()